name: Infrastructure Import using terraform
on:
  workflow_dispatch:
    inputs:
       ACTION:
        description: 'Choose operation'
        required: true
        type: choice
        options: 
          - Copy_Object
          
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

env:
  REGION: us-east-1

jobs:
  Copy_Object:
    if: ${{ github.event.inputs.ACTION == 'Copy_Object' }}
    name: Create Metrics Infrastructure Devl
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
        
      - name: get_aws_credentials_devl
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::875067281875:role/s3_object_copy"
          aws-region: "us-east-1"

      - name: check identity
        run: |
          aws sts get-caller-identity

      - name: Copy object
        run: |
          aws s3 cp s3://mytestbucketzip/DistributorPackages/secagent/  s3://testipdata/DistributorPackages/secagent/ --recursive
